services:
  backend:
    image: node
    mem_limit: 500m
    cpus: 0.3
    volumes:
      - ./backend:/backend
    environment:
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      NODE_ENV: postgresEnv
    ports:
      - 3000:3000
    command: bash -c "cd /backend && npm i && node app"

  database:
    image: postgres
    mem_limit: 500m
    cpus: 0.3
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
