services:
    backend:
        image: node
        volumes:
            - ./backend:/backend
        ports:
            - 3000:3000
        depends_on:
            - db
        command: bash -c "cd /backend && npm i && node app"
    db:
        image: postgres
        environment:
            - "POSTGRES_USER=postgres"
            - "POSTGRES_PASSWORD=postgres"
            - "POSTGRES_DB=db"
        ports:
            - "5432:5432"
        volumes:
            - db:/var/lib/postgressql
volumes:
    db:
