services:
  backend:
    image: node
    mem_limit: 500m
    cpus: 0.3
    volumes:
      - ./backend:/backend:bind
    environment:
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_PORT: ${DB_PORT}
    ports:
      - 3000:3000
    depends_on:
      - postgres-db
    command: bash -c "cd /backend && npm i && node app"
  postgres-db:
    image: postgres
    mem_limit: 500m
    cpus: 0.3
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      #PGDATA: ${POSTGRES_DATA}
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    #- db:${POSTGRES_DATA}
    ports:
      - "5434:5432"
volumes:
  db:
