services:
  backend:
    image: node:21-alpine3.17
    mem_limit: 200m
    cpus: 1
    volumes:
      - ../backend:/backend
    environment:
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      NODE_ENV: mysqlEnv
    ports:
      - 3000:3000
    depends_on:
      - database
    command: /bin/sh -c "cd /backend && npm i && node app"
  database:
    image: mysql:5.7
    mem_limit: 300m
    cpus: 0.3
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
